inquiry/urls.py
from django.urls import path
from . import views
\
urlpatterns = [
    path('', views.inquiry, name='inquiry'),
    path('inquiry_complete/', views.inquiry_complete, name='inquiry_complete'),
]

post/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('post_tweet/', views.post_tweet, name='post_tweet'),
    path('tweet_list/', views.tweet_list, name='tweet_list'),
    path('my_posts/', views.my_posts, name='my_posts'),
    path('like/<int:post_id>/', views.like_tweet, name='like_tweet'),
]

reviewsApp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls import handler404

urlpatterns = [
    path('adminReviewsApp/', admin.site.urls),
    path('account/', include('account.urls')),
    path('inquiry/', include('inquiry.urls')),
    path('', include('post.urls')),
    path('', views.top, name='top'),
    path('terms_of_service/', views.terms_of_service, name='terms_of_service'),
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),
    path('operation_info/', views.operation_info, name='operation_info'),
]

handler404 = views.error_404page
handler500 = views.error_500page

inquiry/models.py
from django.db import models

class Inquiry(models.Model):
    company_name = models.CharField(max_length=100, verbose_name='お名前')
    first_name = models.CharField(max_length=100, verbose_name='名')
    last_name = models.CharField(max_length=100, verbose_name='姓')
    email = models.EmailField(verbose_name='連絡先メールアドレス')
    phone_number = models.CharField(max_length=20, verbose_name='電話番号')
    content = models.TextField(verbose_name='問い合わせ内容')
    created_at = models.DateTimeField(auto_now_add=True,verbose_name='問い合わせ日時')

    class Meta:
        verbose_name = 'お問い合わせ'
        verbose_name_plural = 'お問い合わせ一覧'

    def __str__(self):
        return f"Inquiry from {self.company_name} {self.first_name} {self.last_name} ({self.email})"

inquiry/forms.py
from django import forms
from .models import Inquiry

class InquiryForm(forms.Form):
    company_name = forms.CharField(label='会社名', max_length=30)
    first_name = forms.CharField(label='名', max_length=30)
    last_name = forms.CharField(label='名', max_length=30)
    email = forms.EmailField(label='メールアドレス')
    phone_number = forms.CharField(label='名', max_length=20)
    content = forms.CharField(label='問い合わせ内容',widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

inquiry/views.py
from django.shortcuts import render
from .forms import InquiryForm
from django.core.mail import send_mail

def inquiry(request):
    if request.method == 'POST':
        form = InquiryForm(request.POST)
        if form.is_valid():
            company_name = form.cleaned_data['company_name']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            phone_number = form.cleaned_data['phone_number']
            content = form.cleaned_data['content']
            Inquiry.objects.create(company_name=company_name, first_name=first_name, last_name=last_name, email=email, phone_number=phone_number, content=content)

            subject = '問い合わせを受け付けました'
            html_message = render_to_string('inquiry/mail_template/inquiry/message.html', {
                'company_name': company_name,
                'last_name': last_name,
                'first_name': first_name,
                'email': email,
                'phone_number': phone_number,
                'content': content,
            })
            plain_message = strip_tags(html_message)
            from_email = 'info@MeBias.com'
            to_email = [email]
            send_mail(subject, plain_message, from_email, to_email, html_message=html_message)

            subject = '問い合わせを受け付けました'
            html_message = render_to_string('inquiry/mail_template/inquiry/announce.html', {
                'company_name': company_name,
                'last_name': last_name,
                'first_name': first_name,
                'phone_number': phone_number,
                'email': email,
                'content': content,
            })
            plain_message = strip_tags(html_message)
            from_email = 'info@MeBias.com'
            to_email = ['MeBias.info@gmail.com']
            send_mail(subject, plain_message, from_email, to_email, html_message=html_message)

            return redirect('inquiry_complete')
    else:
        form = InquiryForm()
    return render(request, 'inquiry/inquiry.html', {'form': form})

def inquiry_complete(request):
    return render(request, 'inquiry/inquiry_complete.html')

templates/inquiry/inquiry.html
{% extends 'base.html' %}
{% block title %}
お問い合わせ - {{ block.super }}
{%endblock%}
{% block content %}
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="{% url 'top' %}">トップ</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">お問い合わせ</li>
    </ol>
</nav>
<div class="container">
    <div class="row d-flex align-items-center justify-content-center h-100">
        <div class="col-md-7 col-lg-5 col-xl-5">
            <h5>お問い合わせ</h5>
            <form method="post" action="{% url 'inquiry' %}">
                {% if error_message %}
                <div class="alert alert-danger">
                    {{ error_message }}
                </div>
                {% endif %}
                {% csrf_token %}
                <p>下記のフォームをすべて入力し、「問い合わせる」ボタンを押してください。</p>
                <p></p>
                <div class="form-group mb-3">
                    <label for="id_company_name">会社名</label>
                    <input type="company_name" name="company_name" class="form-control" id="id_company_name" required>
                </div>
                <div class="row mb-3">
                    <div class ='col'>
                    <label for="id_last_name">姓</label>
                    <input type="last_name" name="last_name" class="form-control" id="id_last_name" required>
                    </div>
                    <div class ='col'>
                    <label for="id_first_name">名</label>
                    <input type="first_name" name="first_name" class="form-control" id="id_first_name" required>
                    </div>
                </div>
                <div class="form-group mb-3">
                    <label for="id_email">連絡先メールアドレス</label>
                    <input type="email" name="email" class="form-control" id="id_email" required>
                </div>
                <div class="form-group mb-3">
                    <label for="id_phone_number">連絡先電話番号</label>
                    <input type="tel" name="phone_number" class="form-control" id="id_phone_number" required>
                </div>
                <div class="form-group mb-3">
                    <label for="id_content">問い合わせ内容</label>
                    <textarea name="content" class="form-control" id="id_content" rows="5" required></textarea>
                </div>
                <p><small>ボタンを押すことで、当サービスの<a href="/terms_of_service/" target="_blank">利用規約</a>および<a href="/privacy_policy" target="_blank" >プライバシーポリシー</a>について同意したとみなします。</small></p>
                <button type="submit" class="btn btn-primary w-100 mb-3">問い合わせる</button>
                <a type="button" data-mdb-ripple-init="" class="w-100 btn btn-link mb-3" href="{% url 'top' %}">トップに戻る</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/inquiry/inquiry_complete.html
{% extends 'base.html' %}
{% block title %}
お問い合わせ完了 - {{ block.super }}
{%endblock%}
{% block content %}
{% load static%}
<div class="mt-3">
    <div class="row d-flex align-items-center justify-content-center h-100">
        <div class="col-md-7 col-lg-5 col-xl-5">
            <h5>問い合わせが完了しました！</h5>
            <p>担当よりご登録いたただいたメールアドレス宛にご連絡いたします。今しばらくお待ちください。</p>
            <a type="button" data-mdb-ripple-init="" class="w-100 btn btn-link mb-3" href="{% url 'top' %}">トップに戻る</a>
        </div>
    <div>
<div>
{% endblock %}